/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/Layouts/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/Layouts/SidebarLink.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
